### ISSUE TITLE
[Sentinel-CLI] has been updated to 0.3.2

### ISSUE THREAD

**Issue by guchengdaoke** [Tkd-Alex/dvpn-node-spawner#10]
dvpn-node-spawner/handlers/SentinelCLI.py
14 lines
[Sentinel-CLI] has been updated to 0.3.2

**Comment by Tkd-Alex** [comment]
Hi :) 

The new version of sentinel-cli just fixes an issue related to the sessions, nothing about the key management, we could skip it

https://github.com/sentinel-official/cli-client/commit/c4db21a4c38659b52ff647356eb8e8964df7f40d

But if you prefer to submit a pull request you are welcome :)

**Comment by guchengdaoke** [comment]
> 你好 ：）
> 
> 新版本的sentinel-cli只是修复了与会话相关的问题，没有涉及密钥管理，我们可以跳过它
> 
> [sentinel-official/cli-client@c4db21a](https://github.com/sentinel-official/cli-client/commit/c4db21a4c38659b52ff647356eb8e8964df7f40d)
> 
> 但如果您更愿意提交拉取请求，欢迎您:)

Okay, I know
I thought it was an important update
So, now, you can really ignore him
